language: python

services:
  - xfb

matrix:
 include:
  - os: linux
    python: 3.6

stages:
 - install
 - test
 - deploy

install:
 - pip install -r requirements-dev.txt

script:
 - coverage erase
 - coverage run -a --source ./sksurgeryarucotracker -m pytest -v -s ./tests/
 - coverage report -m
 - pylint --rcfile=tests/pylintrc sksurgeryarucotracker tests

after_success:
 - coveralls

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_existing: true
  on:
   tags: true
   branch: master
